<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Daily Report</title>
    <link rel="icon" href="<?php echo base_url(); ?>assets/image/logo/icon.png">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="<?php echo base_url(); ?>assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="<?php echo base_url(); ?>assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="<?php echo base_url(); ?>assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css"> 
    <link rel="stylesheet" href="<?php echo base_url(); ?>assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="<?php echo base_url(); ?>assets/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
 
    <?php
$name = "";
for ($i=0; $i < strlen($user['employee_name']) ; $i++) { 
    $name = $name.$user['employee_name'][$i];
    if ($user['employee_name'][$i] == " ") {
        break;
    }
}
?>
    <link rel="stylesheet" href="<?php echo base_url(); ?>assets/dist/css/adminlte.min.css">
    <style type="text/css">
        @keyframes ldio-r018sp712d7 {
            0% {
                opacity: 1
            }

            100% {
                opacity: 0
            }
        }

        .ldio-r018sp712d7 div {
            left: 94px;
            top: 48px;
            position: absolute;
            animation: ldio-r018sp712d7 linear 1s infinite;
            background: #ffffff;
            width: 16px;
            height: 24px;
            border-radius: 6px / 16px;
            transform-origin: 6px 52px;
        }

        .ldio-r018sp712d7 div:nth-child(1) {
            transform: rotate(0deg);
            animation-delay: -0.9166666666666666s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(2) {
            transform: rotate(30deg);
            animation-delay: -0.8333333333333334s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(3) {
            transform: rotate(60deg);
            animation-delay: -0.75s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(4) {
            transform: rotate(90deg);
            animation-delay: -0.6666666666666666s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(5) {
            transform: rotate(120deg);
            animation-delay: -0.5833333333333334s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(6) {
            transform: rotate(150deg);
            animation-delay: -0.5s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(7) {
            transform: rotate(180deg);
            animation-delay: -0.4166666666666667s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(8) {
            transform: rotate(210deg);
            animation-delay: -0.3333333333333333s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(9) {
            transform: rotate(240deg);
            animation-delay: -0.25s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(10) {
            transform: rotate(270deg);
            animation-delay: -0.16666666666666666s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(11) {
            transform: rotate(300deg);
            animation-delay: -0.08333333333333333s;
            background: #ffffff;
        }

        .ldio-r018sp712d7 div:nth-child(12) {
            transform: rotate(330deg);
            animation-delay: 0s;
            background: #ffffff;
        }

        .loadingio-spinner-spinner-we5q9gikh8 {
            width: 200px;
            height: 200px;
            display: inline-block;
            overflow: hidden;
            background: none;
        }

        .ldio-r018sp712d7 {
            width: 100%;
            height: 100%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0;
            /* see note above */
        }

        .ldio-r018sp712d7 div {
            box-sizing: content-box;
        }

        /* generated by https://loading.io/ */
        .select2-results__options li {
            color: black;
        }

        footer {
            display: none;
        }

        .color-change-2x {
            -webkit-animation: color-change-2x 2s linear infinite alternate both;
            animation: color-change-2x 2s linear infinite alternate both
        }

        @-webkit-keyframes color-change-2x {
            0% {
                background: #19dcea
            }

            100% {
                background: #b22cff
            }
        }

        @keyframes color-change-2x {
            0% {
                background: #19dcea
            }

            100% {
                background: #b22cff
            }
        }
    </style>
    <?php $url = base_url('Employee/createTemplateReport'); ?>
    <script type="text/javascript">
        function disableButton(btn) {
            document.getElementById(btn.id).disabled = true;
            window.location.href = "<?= $url ?>";
            $("#load1").addClass("d-flex");
        }

        function disableButton2(btn) {
            $("form.form-once-only").submit(function() {
                $(this).find(':button').prop('disabled', true);
                $("#load2").addClass("d-flex");
            });
        }
    </script>
</head>
</style>

<body class="hold-transition sidebar-mini pb-5" id="your-element-selector" >
    <h3 class="text-center text-dark p-4">Daily Report BATS Consulting</h3>
    <div class="wrapper p-3 rounded bg-dark b-5 shadow container"  style="max-width: 1400px;">
        <section class="content">
            <div class="main-body">
                <nav aria-label="breadcrumb" class="main-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item" style="font-size: 16px;"><a href="<?= base_url()?>">Home</a></li>
                        <li class="breadcrumb-item active" style="font-size: 16px;" aria-current="page">Daily Report</li>
                    </ol>
                </nav>
            </div>
            <div class="card bg-dark  shadow-none">
                <div class="card-body p-0">
                    <form action="<?= base_url('Employee/dailyReport'); ?>" method="POST">
                        <div class="row flex-column-reverse flex-lg-row">
                            <input type="hidden" name="type" value="day">
                            <div class="col-md-6 " id="day">
                                <div class="form-group">
                                    <label class="text-white" style="font-size: 16px;">Select date: </label>
                                    <input type="date" style="font-size: 16px;" name="day" class="" value="<?= $date ?>" id="" required>
                                </div>
                                <button type="submit" style="font-size: 16px;" class="btn btn-sm mt-1 btn-default text-dark"><i class="fa fa-search mr-1" style="font-size: 16px;"></i> search</button> <small></small>
                                <a type="button" id="clickupdate" style="font-size: 16px;" class="btn btn-sm mt-1 btn-default text-success"  onclick=" $('#load1').addClass('d-flex');window.location.href='<?= base_url('Employee/updateTemplateDailyReport') ?>';"><small>update template</small><i class="fa fa-database ml-1" style="font-size: 16px;"></i> </a>
                                <br>
                                <p class="p-2 mt-2 shadow rounded" style="background-color: rgba(225,225,225,0.2);">
                                Jika kamu ingin memperbaiki template, misal waktu yang dibuat tidak sampai 24jam, kamu bisa <b>update template</b>, hal ini tidak akan mempengaruhi row yang telah kamu isi.
                                </p>
                            </div>
                            <div class="col-md-6">
                                <div class="callout shadow text-justify" style="background-color: rgba(225,225,225,0.2);">
                                    <h6 style="font-size: 16px;">Please Read!!</h6>
                                    <ul style="font-size: 16px;">
                                        <li class="">Pembuatan template daily report hanya dapat dilakukan pada pukul <b> 00:00</b> sd <b>09:00</b>  di hari itu</li>
                                        <li class="">Jika tidak mengisi daily report di waktu yang terlewat maka akan dianggap <b class="text-danger">tidak bekerja</b> </li>
                                        <li class="">Daily report tidak bisa diperbarui jika sudah melebihi <b>Waktunya</b> </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </form>
                    <?php
                            //   $date == date('Y-m-d') &&
                        if ( empty($dailyReport)) {
                            
                            $time = date('Y-m-d ')."09:50:00";
                            
                            $timestamp = strtotime($time); 
                            
                            if (time() > $timestamp) {
                            ?>
                    <style>
                        .lock {
                            width: 400px;
                            height: 200px;
                            background-color: #fff;
                            border-radius: 10px;
                            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                            display: flex;
                            align-items: center;
                            justify-content: center;
                            flex-direction: column;
                        }

                        .lock-icon {
                            font-size: 72px;
                            color: #f44336;
                            animation: spin 2s linear infinite;
                        }

                        @keyframes spin {
                            0% {
                                transform: rotate(0deg);
                            }

                            100% {
                                transform: rotate(360deg);
                            }
                        }

                        h1 {
                            font-size: 36px;
                            color: #333;
                            text-align: center;
                            margin: 0;
                        }
                    </style>

                    <div style="display: flex; flex-direction: column; align-items: center; width: 80%; margin: 0 auto; border: 1px solid #ccc; border-radius: 5px; padding: 20px;">
                        <h1 class="text-light" style="margin-top: 0; text-align: center;"><?= date('h:i a') ?></h1>
                        <p style="font-size: 18px; line-height: 1.5; margin-bottom: 20px;" class="p-3">
                          Waktu pembuatan daily report telah habis, batas pembuatan template pada pukul <b>00:00</b>  sd <b>08:15</b>
                        </p>
                        <div class="d-flex flex-row justify-content-center p-4 rounded">
                            <div class="lock">
                                <div class="lock-icon">
                                    <i class="fas fa-lock"></i>
                                </div>
                                <h1>Akses Dikunci</h1>
                            </div>
                        </div>

                        <a target="blank" href="https://api.whatsapp.com/send?phone=6285777885964&text=Saya%20terlambat%20melakukan%20get%20template%20karena%20lupa%2C%20apa%20yang%20harus%20saya%20lakukan%3F" class="btn bt-sm btn-success" style="font-size: 14px;">Hubungi admin <i class="fab fa-whatsapp"></i></a>
                    </div>
                    <script>
                        document.getElementById('clickupdate').style.display = "none";
                    </script>
                    <?php
                    
                              } else {
                              ?>
                              <p class="text-center mt-3">
                              cie get template:v jangan lupa isi doingnya :D</p>
                    <div class="d-flex justify-content-center align-items-center p-3">
                        <button class="btn btn-sm btn-warning" id="btn1" onclick="disableButton(this)" style="font-size: 16px;"><i class="fa fa-cogs mr-2"></i> get template</button>
                    </div>
                    <?php
                              }
                            } 
                            else{
                            ?>
                    <div class="d-flex justify-content-between mt-3 align-items-md-end bg-warning">
                        <small style="font-size: 16px;" class=" p-2 "><?=$message?></small>
                    </div>
                    <form method="post" action="<?= base_url('Employee/dailyReport') ?>" class="form-once-only table-responsive" id="formAll">
                        <input type="hidden" name="date" value="<?=$date?>">
                        <table id="table" class="w-100" style="font-size: 16px;">
                            <thead class="thead-inverse text-white">
                                <tr>
                                    <th class=" d-none d-lg-block">#</th>
                                    <th class="text-center">Time</th>
                                    <th class="text-center">Plan</th>
                                    <th class="text-center">Do</th>
                                    <th class="text-center">Problem</th>
                                    <th class="text-center">Solution</th>
                                    <th class="text-center">Description</th>
                                    <!-- <th class="d-none d-lg-block">Status</th> -->
                                </tr>
                            </thead>
                            <tbody class="text-white">
                                <?php
                            $no = 1;
                            foreach ($dailyReport as $key) {
                                 
                                $now = date_create(date('Y-m-d ').$key['end_time']); //now
                                $hours = 10; // hours amount (integer) you want to add
                                $modified = (clone $now)->add(new DateInterval("PT{$hours}H"));
                                $modified = $modified->format('Y-m-d H:i:s');
                                $modified = strtotime($modified); 

                                if($no > 18){
                                     echo '<tr>' ;
                                }else{
                                    echo '<tr style="background-color: rgba(248, 249, 215,0.6); color:black;">';
                                };
                                    $readonly = "";
                                    // || $date != date('Y-m-d')
                                if ($key['check'] == "yes") {
                                    $readonly = "readonly  disabled ";
                                } 


                                $time = date('Y-m-d ').$key['end_time']; // waktu yang ingin dikonversi, dalam format string
                              
                                $timeS = date('Y-m-d ')." 00:00:00";
                                $timeE = date('Y-m-d ')." 08:15:00";
                                $timestamp = strtotime($time); 
                                $timestampS = strtotime($timeS); 
                                $timestampE = strtotime($timeE); 
                                if ($timestamp >= $timestampS && $timestamp < $timestampE  ) {
                                ?>
                                <input type="hidden" name="report_id<?= $no ?>" value="<?=$key['id']?>">
                                      <td class="p-1  text-center d-none d-lg-block"><?= $no ?></td>
                                      <td class="p-1  text-nowrap"><?= date("G:i - ", strtotime($key['start_time'])).date("G:i", strtotime($key['end_time'])) ?></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="planing<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" style=" height:30px; font-size: 16px;background-color:<?php if(empty($key['planing'])){echo "white";}else{ echo "#42d7b5; color : white";}?>" value="<?= $key['planing'] ?>"></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="doing<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['doing'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['doing'])){echo "white";}else{ echo "#42d7b5; color : white";}?>"></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="problem<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['problem'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['problem'])){echo "white";}else{ echo "#42d7b5; color : white";}?>"></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="solution<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['solution'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['solution'])){echo "white";}else{ echo "#42d7b5; color : white";}?>"></td>
                                      <td class="p-1  text-nowrap">
                                          <input name="description<?=$key['id']?>" <?=$readonly?> type="text" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['description'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['description'])){echo "white";}else{ echo "#42d7b5; color : white";}?>">
                                      </td>
                                      <!-- <td class="bg-white p-1 text-nowrap d-none d-lg-block">
                                          <?php
                                              if ($key['planing']&&$key['doing']) {
                                                  echo ( $key['check'] == 'yes') ? '<small class="text-success"> approved</small>' : '<small class="text-warning"> waiting for approval</small>' ; 
                                              } else {
                                                  echo '<small class="text-danger">not filled in</small>' ; 
                                              }
                                              ?>
                                      </td> -->
                                <?php
                                
                                $no++;
                                  } else{
                                    // $modified = strtotime($modified); 
                                    if (time() > $modified) {
                                      if ($key['planing'] == "" || $key['doing'] == "") {
                                        ?>
                                        
                                      <input type="hidden" name="report_id<?= $no ?>" value="<?=$key['id']?>">
                                        <td class="p-1  text-center  d-none d-lg-block"><?= $no ?></td>
                                        <td class="p-1  text-nowrap"><?= date("G:i - ", strtotime($key['start_time'])).date("G:i", strtotime($key['end_time'])) ?></td>
                                        
                                        <td colspan="5" class="text-white text-center" style="background-color: #9C254D;">NOT WORK</td>
                                        <?php
                                        
                                        $no = $no+1;
                                        continue;
                                      } 
                                      
                                      ?>
                                      <input type="hidden" name="report_id<?= $no ?>" value="<?=$key['id']?>">
                                      <td class="p-1  text-center  d-none d-lg-block"><?= $no ?></td>
                                      <td class="p-1  text-nowrap "><?= date("G:i - ", strtotime($key['start_time'])).date("G:i", strtotime($key['end_time'])) ?></td>
                                      <td class="p-1  text-nowrap "><input readonly disabled type="text" <?=$readonly?> name="planing<?=$key['id']?>" class=" border-success w-100 text-success"  value="<?= $key['planing'] ?>"></td>
                                      <td class="p-1  text-nowrap "><input readonly disabled type="text" <?=$readonly?> name="doing<?=$key['id']?>" class=" border-success w-100 text-success" value="<?= $key['doing'] ?>"></td>
                                      <td class="p-1  text-nowrap "><input readonly disabled type="text" <?=$readonly?> name="problem<?=$key['id']?>" class=" border-success w-100 text-success" value="<?= $key['problem'] ?>"></td>
                                      <td class="p-1  text-nowrap "><input readonly disabled type="text" <?=$readonly?> name="solution<?=$key['id']?>" class=" border-success w-100 text-success" value="<?= $key['solution'] ?>"></td>
                                      <td class="p-1  text-nowrap ">
                                          <input readonly disabled name="description<?=$key['id']?>" <?=$readonly?> type="text" class=" border-success w-100 text-success" value="<?= $key['description'] ?>">
                                      </td>
                                      <!-- <td class="bg-white p-1 text-nowrap d-none d-lg-block">
                                          <?php
                                              if ($key['planing']&&$key['doing']) {
                                                  echo ( $key['check'] == 'yes') ? '<small class="text-success"> approved</small>' : '<small class="text-warning"> waiting for approval</small>' ; 
                                              } else {
                                                  echo '<small class="text-danger">not filled in</small>' ; 
                                              }
                                              ?>
                                      </td> -->
                                      <?php
                                    }
                                    else{
                                      ?>
                                      <input type="hidden" name="report_id<?= $no ?>" value="<?=$key['id']?>">
                                      <td class="p-1  text-center d-none d-lg-block"><?= $no ?></td>
                                      <td class="p-1  text-nowrap"><?= date("G:i - ", strtotime($key['start_time'])).date("G:i", strtotime($key['end_time'])) ?></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="planing<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" style=" height:30px; font-size: 16px;background-color:<?php if(empty($key['planing'])){echo "white";}else{ echo "#42d7b5; color : white";}?>" value="<?= $key['planing'] ?>"></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="doing<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['doing'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['doing'])){echo "white";}else{ echo "#42d7b5; color : white";}?>"></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="problem<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['problem'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['problem'])){echo "white";}else{ echo "#42d7b5; color : white";}?>"></td>
                                      <td class="p-1  text-nowrap"><input type="text" <?=$readonly?> name="solution<?=$key['id']?>" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['solution'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['solution'])){echo "white";}else{ echo "#42d7b5; color : white";}?>"></td>
                                      <td class="p-1  text-nowrap">
                                          <input name="description<?=$key['id']?>" <?=$readonly?> type="text" class=" p-1 w-100 <?php if($key['check'] == "yes"){echo "bg-light";}?>" value="<?= $key['description'] ?>" style=" height:30px; font-size: 16px; background-color:<?php if(empty($key['description'])){echo "white";}else{ echo "#42d7b5; color : white";}?>">
                                      </td>
                                      <!-- <td class="bg-white p-1 text-nowrap d-none d-lg-block">
                                          <?php
                                              if ($key['planing']&&$key['doing']) {
                                                  echo ( $key['check'] == 'yes') ? '<small class="text-success"> approved</small>' : '<small class="text-warning"> waiting for approval</small>' ; 
                                              } else {
                                                  echo '<small class="text-danger">not filled in</small>' ; 
                                              }
                                              ?>
                                      </td> -->
                                      <?php
                                    }
                                    
                                    $no++;
                                  }
                                ?>
                                
                                </tr>
                                <?php
                            }
                            ?>

                            </tbody>
                        </table>
                        <input type="hidden" name="totalData" value="<?= $no; ?>">
                        <?php
                            if ($type == "day") {?>
                        <div class="position-fixed fixed-bottom d-flex justify-content-center mb-3">
                            <button type="submit" id="btn2" form="formAll" class="btn btn-sm btn-default mt-3 align-center w-25 text-success border-success" style="font-size: 16px;" onclick="disableButton2(this)"> save <i class="ml-2 fa fa-save"></i></button>
                        </div>
                        <?php
                            }
                            ?>
                    </form>
                    <?php
                            }
                            ?>
                </div>
            </div>
        </section>
    </div>
    <?php
// $homepage = file_get_contents('https://zenquotes.io/api/quotes/');
// $homepage = json_decode($homepage);
// $homepage = $homepage[rand(0, count($homepage) - 1)];
?>
    <div id="load2" style="display: none;" class="justify-content-center flex-column align-items-center position-fixed fixed-top color-change-2x h-100">
        <div class="loadingio-spinner-spinner-we5q9gikh8">
            <div class="ldio-r018sp712d7">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
        <div class="display-6 text-white">
            memperbarui laporan... mohon tunggu
        </div>
    </div>


    <div id="load1" style="display: none;" class="justify-content-center flex-column align-items-center position-fixed fixed-top color-change-2x h-100">
        <div class="loadingio-spinner-spinner-we5q9gikh8">
            <div class="ldio-r018sp712d7">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
        <div class="display-6 text-white">
            sabar yak lagi dibikin nih templatenya.. <br> <br>
            Semakin sulit perjalanan hidupmu, maka kamu akan menjadi semakin kuat :D
        </div>
    </div>
    
    <?php include'footer.php' ?>

    <!-- <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.15.7/dist/sweetalert2.all.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.halo.min.js"></script> -->
    <script>
        // VANTA.HALO({
        // el: "#your-element-selector",
        // mouseControls: true,
        // touchControls: true,
        // gyroControls: false, 
        // minHeight: 200.00,
        // minWidth: 200.00
        // })
    </script>
    <script>
        var update = "<?= $this->session->userdata('update')?>";
        var name = "<?= strtolower($name)?>";
        if (update == "success") {
            Swal.fire({
                position: 'center-center',
                icon: 'success',
                title: "Daily report " + name + " udah diupdate :)",
                showConfirmButton: false,
                timer: 1500
            });
            var printah = "<?= $_SESSION['update'] = "
            no " ?>";
        }
        
        // AOS.init();
    </script>
</body>

</html>